apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-omnia-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: omnia-app
  template:
    metadata:
      labels:
        app: omnia-app
    spec:
      containers:
        - name: omnia-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"